spring:
  application:
    name: spring-boot-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot-auth
    username: sba-user
    password: sba-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect